spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        format_sql: true
  liquibase:
    changelog: classpath:db/changelog/db.changelog-master.xml
    enabled: true

---
spring:
  profiles:
    active: local