spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl-auto: none
  show_sql: true
  format_sql: true

liquibase:
  changelog: classpath:db/changelog/db.changelog-master.xml

